name: Release a NPM Github Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//g; s/[^0-9\.]//g')" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@vitoraguila'

      - name: publish
        run: |
          echo "Release version: ${{env.RELEASE_VERSION}}"
          yarn publish --new-version ${{env.RELEASE_VERSION}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}